
default: &default
  adapter: postgresql
  encoding: unicode
  username: oidowu
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nomster_development

test:
  <<: *default
  database: nomster_test

production:
  <<: *default
  database: nomster_production
  #username: nomster
  #password: <%= ENV['NOMSTER_DATABASE_PASSWORD'] %>
